### ISSUE TITLE
Implicit wait and setScriptTimeout example

### ISSUE THREAD

**Issue by learntolive2** [tabhresh/Edureka_29thJuly#1]
Hi Abhresh,
    I am trying to understand implict wait condition and setScriptTimeout using your example code 
"ImplicitWait.java".  
Here is the snippet from it:
```
               // Implicitly wait
		driver.manage().timeouts().implicitlyWait(120, TimeUnit.SECONDS);

		// SetScript Timeout
		driver.manage().timeouts().setScriptTimeout(40, TimeUnit.SECONDS);
		driver.findElement(By.name("userName")).sendKeys("tutorial");// 0-10
		driver.findElement(By.name("password")).sendKeys("tutorial");// 0-10
		driver.findElement(By.name("login")).click();// 0-10

```
Observation:  The script terminates after the first exception of not finding an element  By.name("userName").   How does this code can demonstrate setScriptTimeout() exception?

Question #2)  Could you please, provide an example to illustrate implict wait?  Also, can you reset the implict wait middle of your script?

**Comment by AbhreshSugandhi** [comment]
check it again it works for me!

**Comment by AbhreshSugandhi** [comment]
Q1) pls ignore using set script as we don't use it and its very tough to display as a demonstration and find a right example to it.
Q2) Implicit Wait can be executed on my site  wait commands page try to click on link text 2 or 3 and it will work
