### ISSUE TITLE
Which version of Chromedriver to be downloaded?

### ISSUE THREAD

**Issue by ShalluP** [tabhresh/Edureka_29thJuly#3]
I get this error: Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 77
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:25:53'.
Do you have any recommended link for that?

**Comment by AbhreshSugandhi** [comment]
Based on the version of your chrome use the same driver version as after 75 version of chrome the chrome driver 2.46 stopped working
