### ISSUE TITLE
Dealing with auto updating Chrome browser

### ISSUE THREAD

**Issue by learntolive2** [tabhresh/Edureka_29thJuly#5]
I found this site helpful to download older version of Chrome browser: https://www.slimjet.com/chrome/google-chrome-old-version.php

Also, to avoid Chrome browser to auto update on Windows OS -- I have seen on many forums, where people suggested to rename "Update" folder under C:\Program Files (x86)\Google

-Vinay

**Comment by AbhreshSugandhi** [comment]
Ok thanks, Vinay will try this!
