### ISSUE TITLE
Can you please show how to scroll up and down the window to particular location. Because I was going through one online example and that I could not understand

### ISSUE THREAD

**Issue by ksharma147** [tabhresh/Edureka_29thJuly#6]

**Comment by AbhreshSugandhi** [comment]
https://www.edureka.co/community/51052/how-to-scroll-up-down-a-page-using-actions-class-in-selenium

**Comment by AbhreshSugandhi** [comment]
https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/interactions/touch/TouchActions.html#scroll-int-int-

In action Class we have scroll method use that and scroll using the xoffset and Yoffset which you can view from inspect element section
